/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'warm-ivory': '#FAF9F5',
        charcoal: '#1D1D1F',
        surface: '#FAF9F5',
        'surface-dim': '#ddd9d9',
        'surface-bright': '#fdf8f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f7f3f2',
        'surface-container': '#f1edec',
        'surface-container-high': '#ebe7e7',
        'surface-container-highest': '#e5e2e1',
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#46464a',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f4f0ef',
        outline: '#77767b',
        'outline-variant': '#c7c6ca',
        'electric-aura-start': '#2A81FF',
        'electric-aura-end': '#9333EA',
        'sunset-vibe-start': '#F97316',
        'sunset-vibe-end': '#EC4899',
        'emerald-pulse-start': '#10B981',
        'emerald-pulse-end': '#14B8A6',
        'sync-synced': '#10B981',
        'sync-pending': '#F59E0B',
        'sync-offline': '#94A3B8',
        primary: {
          DEFAULT: '#1D1D1F',
          container: '#1d1d1f',
          'fixed-dim': '#c8c6c8',
          'fixed': '#e4e2e4',
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#2A81FF',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#1D1D1F',
        },
        'on-primary': '#ffffff',
        'on-primary-container': '#868587',
        secondary: {
          DEFAULT: '#5e5f5c',
          container: '#e0e0dc',
          fixed: '#e3e2df',
          'fixed-dim': '#c7c7c3',
        },
        'on-secondary': '#ffffff',
        'on-secondary-container': '#626360',
      },
      borderRadius: {
        'pill-sm': '1rem',
        'pill-md': '2rem',
        'pill-lg': '3rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Sora', 'sans-serif'],
        sora: ['Sora', 'sans-serif']
      },
      boxShadow: {
        glass: '0 8px 32px 0 rgba(29, 29, 31, 0.06)',
        'glass-dark': '0 8px 32px 0 rgba(0, 0, 0, 0.4)',
        glow: '0 8px 20px rgba(42, 129, 255, 0.2)',
        floating: '0 8px 20px rgba(29, 29, 31, 0.04)',
        'lumio-glass': '0 20px 40px rgba(29, 29, 31, 0.05)'
      }
    },
  },
  plugins: [],
}
